CREATE DATABASE IF NOT EXISTS perf1;

USE perf1;

DROP TABLE IF EXISTS CUSTOMER;

CREATE EXTERNAL TABLE CUSTOMER (
     CUST_ID INT, FNAME STRING, LNAME STRING, STATE CHAR(2) )
  ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY '\t'
  STORED AS TEXTFILE
  LOCATION '/user/user1/perf/1/customer/';

DROP TABLE IF EXISTS PURCHASE;

CREATE EXTERNAL TABLE PURCHASE (
     CUST_ID INT, PURCH_TS TIMESTAMP, SKU_NBR INT, 
     CATEGORY STRING, PRICE DECIMAL(9,2), DESCRIPTION STRING )
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '\t'
  STORED AS TEXTFILE
  LOCATION '/user/user1/perf/1/purchase/';